-- 1. Bersihkan aturan default lama (jika ada) untuk menghindari konflik
ALTER TABLE public.system_settings ALTER COLUMN id DROP IDENTITY IF EXISTS;

-- 2. Pasang mesin tiket otomatis (Identity) standar Enterprise
ALTER TABLE public.system_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- 3. Putar mesin ke nomor tertinggi agar tidak menabrak data yang sudah ada
SELECT setval(pg_get_serial_sequence('public.system_settings', 'id'), COALESCE((SELECT MAX(id) FROM public.system_settings), 0) + 1, false);